server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #nacos 服务中心注册地址
        server-addr: 192.168.87.128:80
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        #dashboard: localhost:8080
        dashboard: 192.168.87.128:8080
        #默认8719端口，假如被占用会自动从8719开始一次+1扫描，直至找到未被占用的端口
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'
